version: '3.8'
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fsapps_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    expose:
      - "3306"
    healthcheck:
      test: ["CMD-SHELL", "exit | mariadb -h localhost -P 3306 -u root -p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 20s
      retries: 5
  api:
    container_name: fsapps-api
    build: .
    ports:
      - "8000:8000"
    expose:
      - 8000
    environment:
      - SECRET_KEY=secret
      - ACCESS_TOKEN_EXPIRE_MINUTES=15
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
      - APP_DEBUG=False
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASS=password
      - DB_NAME=fsapps_db
    depends_on:
      db:
        condition: service_healthy
